repos:
  # Make sure that Jupyter notebooks under version control
  # have their outputs stripped before committing
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: ".ipynb"
